# Generated by Django 4.1 on 2022-08-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=60),
        ),
    ]
