version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: python-runner
    command: gunicorn instapwn.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - 8080:80
    environment:
      - NGINX_UPSTREAM_URL=web
